[2022-09-09 01:15:03,529] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example3.t1 manual__2022-09-08T17:07:36.033114+00:00 [queued]>
[2022-09-09 01:15:03,544] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example3.t1 manual__2022-09-08T17:07:36.033114+00:00 [queued]>
[2022-09-09 01:15:03,545] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-09 01:15:03,545] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-09-09 01:15:03,545] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-09 01:15:03,563] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t1> on 2022-09-08 17:07:36.033114+00:00
[2022-09-09 01:15:03,566] {standard_task_runner.py:52} INFO - Started process 18382 to run task
[2022-09-09 01:15:03,573] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'example3', 't1', 'manual__2022-09-08T17:07:36.033114+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/example3.py', '--cfg-path', '/var/folders/ll/lb_b4vvx7cgfp2wpfsv4w6zm0000gn/T/tmp8zzf5ji8', '--error-file', '/var/folders/ll/lb_b4vvx7cgfp2wpfsv4w6zm0000gn/T/tmpxhknq04b']
[2022-09-09 01:15:03,574] {standard_task_runner.py:80} INFO - Job 52: Subtask t1
[2022-09-09 01:15:03,657] {task_command.py:371} INFO - Running <TaskInstance: example3.t1 manual__2022-09-08T17:07:36.033114+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-09-09 01:15:03,730] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example3
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2022-09-08T17:07:36.033114+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-08T17:07:36.033114+00:00
[2022-09-09 01:15:03,757] {local_task_job.py:156} INFO - Task exited with return code -11
[2022-09-09 01:15:03,780] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=example3, task_id=t1, execution_date=20220908T170736, start_date=20220908T171503, end_date=20220908T171503
[2022-09-09 01:15:03,816] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
